export const StoreLinks = [
    {
        name: "Dashboard",
        link: "#",
        icon: "carbon:dashboard",
        links: [
            { name: "Master Dashboard", link: "/dashboard" },
            { name: "Counter Dashboard", link: "/counter-dashboard" },
        ],
    },
    {
        name: "Stores",
        link: "#",
        icon: "bx:store",
        links: [
            { name: "Add Store", link: "/stores/create" },
            { name: "List Store", link: "/stores/list" },
        ],
    },
    {
        name: "Sale",
        link: "#",
        icon: "mdi:point-of-sale",
        links: [
            { name: "POS Screen", link: "/stores/create" },
            { name: "List Sale", link: "/stores/list" },
            { name: "Return Sale", link: "/stores/list" },
        ],
    },
    {
        name: "Customers",
        link: "#",
        icon: "carbon:customer",
        links: [
            { name: "Add Customer", link: "/stores/create" },
            { name: "List Customer", link: "/stores/list" },
            { name: "Add Customer Group", link: "/stores/create" },
            { name: "List Customer Group", link: "/stores/list" },
        ],
    },
    {
        name: "Suppliers",
        link: "#",
        icon: "carbon:scis-transparent-supply",
        links: [
            { name: "Add Supplier", link: "/stores/create" },
            { name: "List Supplier", link: "/stores/list" },
        ],
    },
    {
        name: "Services/Products",
        link: "#",
        icon: "fluent-mdl2:product-variant",
        links: [
            { name: "Add Item", link: "/stores/create" },
            { name: "List Item", link: "/stores/list" },
            { name: "Add Category", link: "/stores/create" },
            { name: "List Category", link: "/stores/list" },
            { name: "Add Unit", link: "/stores/create" },
            { name: "List Unit", link: "/stores/list" },
            { name: "Add Brand", link: "/stores/create" },
            { name: "List Brand", link: "/stores/list" },
            { name: "Add Variant", link: "/stores/create" },
            { name: "List Variant", link: "/stores/list" },
            { name: "Print Barcode", link: "/stores/list" },
        ],
    },
    {
        name: "Stocks",
        link: "/stocks",
        icon: "fxemoji:stockchart",
        links: [],
    },
    {
        name: "Purchases",
        link: "#",
        icon: "icon-park-outline:buy",
        links: [
            { name: "Add Purchase", link: "/stores/create" },
            { name: "List Purchase", link: "/stores/list" },
            { name: "Return Purchase", link: "/stores/list" },
        ],
    },
    {
        name: "Expenses",
        link: "#",
        icon: "arcticons:day-to-day-expenses",
        links: [
            { name: "Add Expense", link: "/stores/create" },
            { name: "List Expense", link: "/stores/list" },
            { name: "Add Expense Category", link: "/stores/create" },
            { name: "List Expense Category", link: "/stores/list" },
        ],
    },
    {
        name: "Accounting",
        link: "#",
        icon: "material-symbols:account-balance-outline-rounded",
        links: [
            { name: "Add Account", link: "/stores/create" },
            { name: "List Account", link: "/stores/list" },
            { name: "Add Deposit/Withdraw", link: "/stores/create" },
            { name: "List Deposit/Withdraw", link: "/stores/list" },
            { name: "Balance Statement", link: "/stores/list" },
            { name: "Trial Balance", link: "/stores/list" },
            { name: "Balance Sheet", link: "/stores/list" },
        ],
    },
    {
        name: "Incomes",
        link: "#",
        icon: "tdesign:money",
        links: [
            { name: "Add Income", link: "/stores/create" },
            { name: "List Income", link: "/stores/list" },
            { name: "Add Income Category", link: "/stores/create" },
            { name: "List Income Category", link: "/stores/list" },
        ],
    },
    {
        name: "Quotations",
        link: "#",
        icon: "hugeicons:estimate-01",
        links: [
            { name: "Add Quotation", link: "/stores/create" },
            { name: "List Quotation", link: "/stores/list" },
        ],
    },
    {
        name: "Transfers",
        link: "#",
        icon: "mingcute:transfer-fill",
        links: [
            { name: "Add Transfer", link: "/stores/create" },
            { name: "List Transfer", link: "/stores/list" },
        ],
    },
    {
        name: "Damages",
        link: "#",
        icon: "ri:file-damage-fill",
        links: [
            { name: "Add Damage", link: "/stores/create" },
            { name: "List Damage", link: "/stores/list" },
        ],
    },
    {
        name: "HR Management",
        link: "#",
        icon: "hugeicons:permanent-job",
        links: [
            { name: "Add Employee", link: "/stores/create" },
            { name: "List Employee", link: "/stores/list" },
            { name: "List Payroll", link: "/stores/list" },
            { name: "Add Attendance", link: "/stores/list" },
            { name: "List Attendance", link: "/stores/list" },
        ],
    },
    {
        name: "Report",
        link: "#",
        icon: "fluent-mdl2:report-document",
        links: [
            { name: "Register Report", link: "/stores/create" },
            { name: "Z Report", link: "/stores/list" },
            { name: "Daily Summary Report", link: "/stores/list" },
            { name: "Sale Report", link: "/stores/list" },
            { name: "Service Sale Report", link: "/stores/list" },
            { name: "Stock Report", link: "/stores/list" },
            { name: "Employee Sale Report", link: "/stores/list" },
            { name: "Customer Receive Report", link: "/stores/list" },
            { name: "Attendance Report", link: "/stores/list" },
            { name: "Product Profit Report", link: "/stores/list" },
            { name: "Supplier Ledger", link: "/stores/list" },
            { name: "Supplier Balance Report", link: "/stores/list" },
            { name: "Customer Ledger", link: "/stores/list" },
            { name: "Customer Balance Report", link: "/stores/list" },
            { name: "Servicing Report", link: "/stores/list" },
            { name: "Product Sale Report", link: "/stores/list" },
            { name: "Tax Report", link: "/stores/list" },
            { name: "Detailed Sale Report", link: "/stores/list" },
            { name: "Low Stock Report", link: "/stores/list" },
            { name: "Profit Loss Report", link: "/stores/list" },
            { name: "Purchase Report", link: "/stores/list" },
            { name: "Product Purchase Report", link: "/stores/list" },
            { name: "Expense Report", link: "/stores/list" },
            { name: "Income Report", link: "/stores/list" },
            { name: "Salary Report", link: "/stores/list" },
            { name: "Purchase Return Report", link: "/stores/list" },
            { name: "Sale Return Report", link: "/stores/list" },
            { name: "Damage Report", link: "/stores/list" },
            { name: "Installment Report", link: "/stores/list" },
            { name: "Item Movement Report", link: "/stores/list" },
            { name: "Price History Report", link: "/stores/list" },
            { name: "Cash Flow Report", link: "/stores/list" },
            { name: "Available Loyalty Point Report", link: "/stores/list" },
            { name: "Usage Loyalty Point Report", link: "/stores/list" },
        ],
    },
    {
        name: "System",
        link: "#",
        icon: "hugeicons:solar-system",
        links: [
            { name: "Add Counter", link: "/stores/create" },
            { name: "List Counter", link: "/stores/list" },
            { name: "Add Tax/Vat", link: "/stores/list" },
            { name: "List Tax/Vat", link: "/stores/list" },
            { name: "Add Currency", link: "/stores/list" },
            { name: "List Currency", link: "/stores/list" },
            { name: "Add Payment Gateway", link: "/stores/list" },
            { name: "List Payment Gateway", link: "/stores/list" },
        ],
    },
];
