import ReduxProvider from "@/providers/ReduxProvider";
import { createTheme, MantineProvider } from "@mantine/core";
import { Analytics } from "@vercel/analytics/react";
import { SpeedInsights } from "@vercel/speed-insights/next";
import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import NextTopLoader from "nextjs-toploader";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import "../styles/globals.css";

const outfit = Outfit({
    subsets: ["latin"],
    weight: ["400", "500", "600", "700"],
});

const theme = createTheme({
    fontFamily: outfit.style.fontFamily,
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={outfit.className}>
                <NextTopLoader />
                {process.env.NODE_ENV !== "development" && (
                    <>
                        <Analytics />
                        <SpeedInsights />
                    </>
                )}
                <ReduxProvider>
                    <ToastContainer />
                    <MantineProvider theme={theme} withCssVariables>
                        {children}
                    </MantineProvider>
                </ReduxProvider>
            </body>
        </html>
    );
}
